version: '3'
services:
  consul:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
    networks:
      - backend
  demo:
    image: demo
    build: .
    ports:
      - "80:80"
    networks:
      - backend
networks:
  backend:
